### ISSUE TITLE
NFTombs Odds & NFT Visual Imrpovements

### ISSUE THREAD

**Issue by rugzombie** [Rug-Zombie/rug-zombie-frontend#88]
Adding the Odds for each bracket for NFTs, calculating the wallets current odds, and displaying the available NFTs to earn.

**Comment by nnamdiarimah** [comment]
The amount you stake in NFTombs puts you in different brackets, giving you better odds at rarer nfts. Our page currently doesnt show this so we would like to make this visible to users.

<img width="892" alt="Screen Shot 2022-05-13 at 3 39 50 PM" src="https://user-images.githubusercontent.com/10407499/168378236-765d0fad-a4fd-4afc-bf67-0f8ae328c0ea.png">

<img width="764" alt="Screen Shot 2022-05-13 at 4 31 50 PM" src="https://user-images.githubusercontent.com/10407499/168385162-47c6dda0-7926-4ef5-b9af-ad9cb5dc8997.png">

We would like to add a second progress bar below the existing one:
This progress bar will have 3 sections, instead of containing numbers `1, 2, 3` like the other bar this will contain letters `A,B, C`, representing the bracket a user is in. Instead of the new bar saying `Pair Lp`, `Approve LP`, `Stake LP` it can show the amount of LP needed to get into the bracket.

**Bracket A:**
- If a user has less than 5% of the total tombs lp

**Bracket B:**
- If a user has between 5% and 10% of the total tombs lp

**Bracket C:**
- If has more than 10% of the total tombs lp

**Note:**
Users amount staked: `userInfo.amount`
Total tombs lp: `poolInfo.tokenAmount`

**Comment by nnamdiarimah** [comment]
https://github.com/Rug-Zombie/rug-zombie-frontend/pull/115
